// Generates supabase/seed.sql from content/packs/*.json.
// Local/CI databases get the library packs as status='live' on every
// `db reset` (config.toml seeds sql_paths). Production ingestion follows the
// §9 ritual instead: insert as 'qa_pending', flip to 'live' after QA sign-off
// — pass --status qa_pending and pipe the output through the release runbook.
//
// Usage: node scripts/build-seed.mjs [--status live|qa_pending] [--stdout]
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const packsDir = join(root, "content", "packs");
const outFile = join(root, "supabase", "seed.sql");

const args = process.argv.slice(2);
const status = args.includes("--status") ? args[args.indexOf("--status") + 1] : "live";
const toStdout = args.includes("--stdout");
if (!["live", "qa_pending"].includes(status)) {
  console.error(`invalid --status ${status}`);
  process.exit(1);
}

const q = (s) => `'${String(s).replaceAll("'", "''")}'`; // sql string literal
const qj = (v) => `${q(JSON.stringify(v))}::jsonb`;
const qarr = (v) => `array[${v.map((x) => q(x)).join(", ")}]`;

const files = readdirSync(packsDir).filter((f) => f.endsWith(".json")).sort();
if (files.length === 0) {
  console.error(`no packs found in ${packsDir}`);
  process.exit(1);
}

let sql = `-- GENERATED by scripts/build-seed.mjs — do not edit by hand.
-- Source of truth: content/packs/*.json (QA'd per the brain's question-style-guide).
-- Packs seed as status='${status}'.
`;

for (const file of files) {
  const pack = JSON.parse(readFileSync(join(packsDir, file), "utf8"));
  const rows = pack.questions
    .map((question) => {
      const options = question.options === null ? "null" : qj(question.options);
      return `    (v_pack, ${question.round}, ${question.position}, ${q(question.format)}, ${q(question.prompt)}, ${options}, ${qj(question.answer)}, ${q(question.answer_note)}, ${question.difficulty}, ${question.time_limit_s})`;
    })
    .join(",\n");

  sql += `
-- ${pack.title} (${file})
do $seed$
declare
  v_pack uuid;
begin
  insert into packs (title, topic, description, difficulty_curve, question_count, rounds, source, status, tags, created_by)
  values (${q(pack.title)}, ${q(pack.topic)}, ${q(pack.description)}, array[${pack.difficulty_curve.join(", ")}], ${pack.question_count}, ${pack.rounds}, 'library', ${q(status)}, ${qarr(pack.tags)}, 'seed')
  returning id into v_pack;

  insert into pack_questions (pack_id, round, position, format, prompt, options, answer, answer_note, difficulty, time_limit_s)
  values
${rows};
end $seed$;
`;
}

if (toStdout) {
  process.stdout.write(sql);
} else {
  writeFileSync(outFile, sql);
  console.log(`wrote ${outFile} (${files.length} packs, status=${status})`);
}
