-- ============================================================================
-- PRODUCT SCHEMA — PRD §4, converted to the initial migration.
-- The product OWNS these tables; the org reads/writes only where PRD §9 says so.
--
-- RLS posture (M0 baseline, finalized in M6):
--   * RLS enabled on EVERY product table.
--   * Players get no direct table access — game flows go through
--     server-validated functions (M1). Deny-by-default until then.
--   * The few safe public reads are granted here: live packs (this policy IS
--     the PRD's hard rule "never surface non-live packs" enforced at the DB),
--     active host lines, active ad creatives.
--   * Venue-scoped reads via is_venue_member().
-- ============================================================================

-- ============ identity ============
-- Venue owners/managers use Supabase Auth (magic link). Players are anonymous
-- by default; an account is created only at the post-game save moment.
create table profiles (              -- player accounts (post-game save)
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  home_metro text,
  created_from_game uuid,            -- attribution: the game that converted them
  created_at timestamptz default now()
);

create table venue_members (         -- which auth users manage which venue
  venue_id uuid references venues(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  role text default 'owner' check (role in ('owner','staff')),
  primary key (venue_id, user_id)
);
create index on venue_members (user_id);

-- `venues` exists in the org schema; the product adds its columns (PRD §4):
alter table venues add column slug text unique, add column settings jsonb default '{}';

-- ============ content ============
create table packs (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  topic text not null,
  description text,
  difficulty_curve numeric[],        -- per-round target means, e.g. {2.2,2.8,3.2,3.0}
  question_count int not null,
  rounds int not null default 4,
  source text not null default 'library' check (source in ('library','custom')),
  venue_id uuid references venues(id),          -- set for custom packs
  status text not null default 'draft'
    check (status in ('draft','qa_pending','live','retired','rejected')),
  qa_report jsonb,                   -- written by org trivia-qa agent
  tags text[] default '{}',
  created_by text not null default 'org',       -- 'org' | 'seed' | future sources
  created_at timestamptz default now()
);
create index on packs (status);
create index on packs (venue_id);
-- HARD RULE (also enforced in code): the product only ever surfaces packs with
-- status='live'. Only the org's trivia-qa flips qa_pending->live.

create table pack_questions (
  id uuid primary key default gen_random_uuid(),
  pack_id uuid references packs(id) on delete cascade,
  round int not null, position int not null,
  format text not null default 'multiple_choice'
    check (format in ('multiple_choice','true_false','number_closest','open_text')),
  prompt text not null,
  options jsonb,                     -- ["a","b","c","d"] for multiple_choice
  answer jsonb not null,             -- canonical answer; for open_text include accepted variants
  answer_note text,                  -- shown at reveal ("source: ...") — required by style guide
  difficulty numeric(2,1) not null check (difficulty between 1 and 5),
  time_limit_s int not null default 30,
  unique (pack_id, round, position)
);

create table host_lines (            -- auto-host personality, data-driven (org-updatable, no deploys)
  id uuid primary key default gen_random_uuid(),
  slot text not null check (slot in ('lobby','round_intro','pre_reveal','post_reveal_correct',
    'post_reveal_brutal','intermission','final_intro','podium','close')),
  text text not null,
  tone text default 'default',       -- future: venue-selectable voice packs
  tts_audio_path text,               -- Supabase Storage path; pre-generated by org, played by console
  active boolean default true
);
create index on host_lines (slot) where active;

create table custom_pack_requests (  -- premium feature; fulfilled by org agents
  id uuid primary key default gen_random_uuid(),
  venue_id uuid references venues(id) not null,
  topic text not null,
  notes text,
  question_count int default 40,
  status text not null default 'requested'
    check (status in ('requested','generating','qa','delivered','failed')),
  pack_id uuid references packs(id), -- set on delivery
  requested_at timestamptz default now(),
  delivered_at timestamptz
);
create index on custom_pack_requests (venue_id);

-- ============ live games ============
create table games (
  id uuid primary key default gen_random_uuid(),
  venue_id uuid references venues(id) not null,
  pack_id uuid references packs(id) not null,
  join_code text not null unique,    -- 4-char, unambiguous alphabet (no 0/O/1/I)
  scheduled_for timestamptz,
  state text not null default 'lobby'
    check (state in ('lobby','round_intro','question','locked','reveal','scores',
                     'intermission','final_question','podium','ended','abandoned')),
  current_round int default 0, current_position int default 0,
  settings jsonb default '{}',       -- speed_bonus, roast_mode, tts_enabled, sponsor_slot, etc.
  started_at timestamptz, ended_at timestamptz,
  created_at timestamptz default now()
);
create index on games (venue_id, created_at desc);

create table game_teams (
  id uuid primary key default gen_random_uuid(),
  game_id uuid references games(id) on delete cascade,
  name text not null,                -- profanity-filtered, 24 chars max
  score numeric(8,2) default 0,
  unique (game_id, name)
);
create index on game_teams (game_id);

create table game_players (
  id uuid primary key default gen_random_uuid(),
  game_id uuid references games(id) on delete cascade,
  team_id uuid references game_teams(id) on delete cascade,
  display_name text not null,
  profile_id uuid references profiles(id),      -- null until/unless they save
  device_key text not null,          -- anonymous session token for reconnect/idempotency
  joined_at timestamptz default now(),
  last_seen timestamptz default now()
);
create index on game_players (game_id);
create index on game_players (team_id);
create index on game_players (game_id, device_key);

create table answers (
  id uuid primary key,               -- CLIENT-GENERATED uuid => idempotent retries
  game_id uuid references games(id) on delete cascade,
  question_id uuid references pack_questions(id),
  team_id uuid references game_teams(id),
  player_id uuid references game_players(id),
  payload jsonb not null,
  submitted_at timestamptz default now(),       -- server clock only
  is_correct boolean, points numeric(6,2),      -- filled at reveal by scoring function
  unique (game_id, question_id, team_id)        -- one answer per team per question (first locks)
);
create index on answers (game_id, question_id);
create index on answers (team_id);
create index on answers (player_id);

-- ============ feedback & quality (org-operated queues) ============
create table question_disputes (     -- the live "challenge" button
  id uuid primary key default gen_random_uuid(),
  game_id uuid references games(id), question_id uuid references pack_questions(id),
  team_id uuid references game_teams(id),
  claim text,
  status text default 'open' check (status in ('open','upheld','rejected')),
  ruling_note text, ruled_at timestamptz,        -- written by org trivia-qa within 24h
  created_at timestamptz default now()
);
create index on question_disputes (status, created_at);
create index on question_disputes (game_id);

create table feedback (
  id uuid primary key default gen_random_uuid(),
  source text not null check (source in ('player','venue')),
  game_id uuid references games(id), venue_id uuid references venues(id),
  body text not null, contact_email text,
  status text default 'new' check (status in ('new','triaged','done')),
  created_at timestamptz default now()
);
create index on feedback (status, created_at);

-- ============ ads scaffolding (config-driven; no ad network) ============
create table ad_creatives (
  id uuid primary key default gen_random_uuid(),
  kind text not null check (kind in ('house','sponsor','venue_promo')),
  sponsor_id uuid references sponsors(id),       -- org table
  venue_id uuid references venues(id),           -- for venue_promo (premium)
  surface text not null check (surface in ('screen','phone')),
  asset_path text, headline text, body text, cta_url text,
  active boolean default true,
  created_at timestamptz default now()
);
create index on ad_creatives (venue_id);

-- ============ telemetry (the org's sensory input) ============
create table analytics_events (
  id bigint generated always as identity primary key,
  event text not null,               -- taxonomy in PRD §8 — names are FROZEN
  game_id uuid, venue_id uuid, team_id uuid, player_id uuid, profile_id uuid,
  props jsonb default '{}',
  created_at timestamptz default now()
);
create index on analytics_events (event, created_at);
create index on analytics_events (venue_id, created_at);

-- ============ RLS ============
-- Helper: is the signed-in user a member of this venue? SECURITY DEFINER so
-- policies can consult venue_members without recursive RLS.
create or replace function public.is_venue_member(v_venue uuid)
returns boolean
language sql stable security definer
set search_path = public
as $$
  select exists (
    select 1 from venue_members
    where venue_id = v_venue and user_id = (select auth.uid())
  );
$$;

alter table profiles enable row level security;
create policy "profiles: read own" on profiles
  for select using ((select auth.uid()) = id);
create policy "profiles: update own" on profiles
  for update using ((select auth.uid()) = id);

alter table venue_members enable row level security;
create policy "venue_members: read own memberships" on venue_members
  for select using ((select auth.uid()) = user_id);

-- venues is an org table (RLS enabled in the org migration); the product adds
-- the member-scoped read its dashboard needs.
create policy "venues: members read their venue" on venues
  for select using (public.is_venue_member(id));

alter table packs enable row level security;
create policy "packs: only live are visible" on packs
  for select using (status = 'live');

alter table pack_questions enable row level security;
-- No public policy: question rows carry answers. The console receives question
-- payloads through server-validated game state, never by reading this table.

alter table host_lines enable row level security;
create policy "host_lines: active are public" on host_lines
  for select using (active);

alter table custom_pack_requests enable row level security;
create policy "custom_pack_requests: venue members read" on custom_pack_requests
  for select using (public.is_venue_member(venue_id));

alter table games enable row level security;
create policy "games: venue members read" on games
  for select using (public.is_venue_member(venue_id));

alter table game_teams enable row level security;
alter table game_players enable row level security;
alter table answers enable row level security;
-- No policies yet: all live-game reads/writes go through server-validated
-- functions that land with M1 (players never touch tables directly — PRD §3).

alter table question_disputes enable row level security;
alter table feedback enable row level security;
-- Writes land via server functions with their features (M5).

alter table ad_creatives enable row level security;
create policy "ad_creatives: active are public" on ad_creatives
  for select using (active);

alter table analytics_events enable row level security;
-- Insert-only via server functions; the org's analyst reads with service role.

-- ============ grants ============
-- Supabase no longer auto-exposes new tables to the API roles: RLS policies
-- gate ROWS, these grants gate the TABLES. Grant only what a policy above
-- makes safe; everything else stays reachable through server-validated
-- functions only (which carry their own grants when they land).
grant select on packs, host_lines, ad_creatives to anon, authenticated;
grant select on venues, custom_pack_requests, games, profiles, venue_members
  to authenticated;
grant update (display_name, home_metro) on profiles to authenticated;
grant execute on function public.is_venue_member(uuid) to authenticated;
