-- ============================================================================
-- ORG SCHEMA (layer 2) — MIRROR
-- Source of truth: trivia-bot-brain/infra/supabase-schema.sql
-- These tables are OWNED by the org daemon (trivia-bot-org). They are mirrored
-- here so local/CI/preview databases have them (product tables FK into venues
-- and sponsors). Do not edit this file without updating the brain repo first —
-- the org handoff contract (PRD §9) treats these as a frozen interface.
--
-- Additions vs the brain file, noted and PR'd back to the brain:
--   * `events` table — PRD §4/§9 require the product to insert a row on venue
--     signup that the daemon's CX flow consumes. (`org_flags` from PRD §4 is
--     left to the org daemon build — the product never touches it.)
--   * RLS enabled on every org table with no policies: only the daemon's
--     service role (which bypasses RLS) can touch them. The brain schema file
--     defers RLS to "before any external exposure" — the product IS that
--     exposure, so it lands here.
-- ============================================================================

create extension if not exists pgcrypto;

-- ============ work coordination ============
create table tasks (
  id uuid primary key default gen_random_uuid(),
  dept text not null check (dept in ('brain','marketing','cx','trivia-ops','biz-ops')),
  agent text,                          -- assigned agent key from registry, null = director triages
  title text not null,
  detail text,                         -- self-contained context; receiver has no memory of sender's run
  status text not null default 'open' check (status in ('open','claimed','done','blocked','archived')),
  priority int not null default 3 check (priority between 1 and 5),   -- 1 = highest
  created_by text not null,            -- agent key or 'owner'
  due date,
  output_ref text,                     -- artifact link: PR url, row id, message id, file path
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index on tasks (dept, status, priority);

create table runs (
  id uuid primary key default gen_random_uuid(),
  agent text not null,
  started_at timestamptz default now(),
  finished_at timestamptz,
  status text default 'running' check (status in ('running','ok','failed','killed')),
  tasks_touched uuid[],
  spend_usd numeric(8,4) default 0,    -- inference + tools attributed to this run
  report_path text,                    -- reports/YYYY-MM-DD-<agent>.md
  notes text
);
create index on runs (agent, started_at desc);

create table approvals (
  id uuid primary key default gen_random_uuid(),
  action_class text not null,          -- matches policies matrix
  summary text not null,
  recommendation text,
  requested_by text not null,
  status text default 'pending' check (status in ('pending','approved','rejected','expired')),
  decided_at timestamptz,
  decided_note text,
  created_at timestamptz default now()
);

create table incidents (
  id uuid primary key default gen_random_uuid(),
  severity text check (severity in ('low','med','high','critical')),
  title text not null, body text,
  filed_by text, playbook_diff_ref text,   -- required within 72h per policy §6
  status text default 'open' check (status in ('open','resolved')),
  created_at timestamptz default now()
);

-- ============ funnel ============
create table leads (
  id uuid primary key default gen_random_uuid(),
  venue_name text not null, metro text not null, address text, website text,
  contact_name text, contact_role text, contact_email text,
  evidence jsonb not null default '[]',    -- [{note, source_url}] — outreach personalization lives here
  score numeric(3,2), status text default 'new'
    check (status in ('new','enriched','sequenced','replied','signed_up','nurture','suppressed','archived')),
  suppressed_reason text,
  created_at timestamptz default now(), updated_at timestamptz default now()
);
create index on leads (metro, status, score desc);

create table outreach_events (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid references leads(id),
  sequence text not null, touch int not null,
  message_id text,                       -- artifact
  event text not null check (event in ('sent','delivered','bounced','replied','unsubscribed','complaint')),
  meta jsonb, created_at timestamptz default now()
);
create index on outreach_events (sequence, event, created_at);

-- ============ customers ============
create table venues (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid references leads(id),
  name text not null, metro text, tz text default 'America/Detroit',
  status text default 'onboarding' check (status in ('onboarding','active','at_risk','inactive','churned')),
  premium boolean default false, stripe_customer_id text,
  first_night date, last_night date, nights_run int default 0,
  health jsonb default '{}',             -- {attendance_trend, checklist, notes}
  created_at timestamptz default now()
);

create table sponsors (
  id uuid primary key default gen_random_uuid(),
  business text not null, contact_email text, package text, mrr_usd numeric(8,2),
  venues uuid[], status text default 'prospect'
    check (status in ('prospect','pitched','proposal','signed','live','churned')),
  io_ref text,                           -- signed doc reference (owner-executed)
  created_at timestamptz default now()
);

-- ============ money & metrics ============
create table ledger (
  id uuid primary key default gen_random_uuid(),
  entry_date date not null default current_date,
  kind text not null check (kind in ('inference','tool','infra','revenue','refund','other')),
  agent text, dept text, amount_usd numeric(10,2) not null,  -- negative = cost
  memo text, artifact_ref text
);
create index on ledger (entry_date, dept);

create table kpis_daily (
  day date primary key,
  metrics jsonb not null,   -- keys per brain/kpi-definitions.md
  note text
);

-- ============ org event bus (addition — see header) ============
-- The product's only write obligation to the org besides analytics: a row on
-- venue signup ({"kind":"venue_signup"}) that wakes the daemon's CX flow (PRD §4, §9).
create table events (
  id uuid primary key default gen_random_uuid(),
  kind text not null,
  payload jsonb not null default '{}',
  processed_at timestamptz,             -- daemon marks consumption
  created_at timestamptz default now()
);
create index on events (kind, created_at);

-- ============ RLS: org tables are daemon-only ============
-- No policies on purpose: anon/authenticated get nothing; the daemon's
-- service role bypasses RLS. The product touches org tables only where PRD §9
-- allows, via security-definer functions that land with those features.
alter table tasks enable row level security;
alter table runs enable row level security;
alter table approvals enable row level security;
alter table incidents enable row level security;
alter table leads enable row level security;
alter table outreach_events enable row level security;
alter table venues enable row level security;
alter table sponsors enable row level security;
alter table ledger enable row level security;
alter table kpis_daily enable row level security;
alter table events enable row level security;
